modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="royalrealms"
version="1.0.0"
displayName="RoyalRealms"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="saver, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.royalrealms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.royalrealms]]
    modId="cosmetic_armory"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.royalrealms]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration